import { setSlotPhoto } from "@/app/router/book/set-slot-photo";
import { uploadSlotPhoto } from "@/app/router/book/upload-slot-photo";
import type { Organization, Store, User } from "@/generated/prisma/client";
import prisma from "@/lib/db";
import { call } from "@orpc/server";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import {
  createMember,
  createOrg,
  createUser,
  resetDb,
  s2sContext,
} from "./helpers";

const KEY = "books/upload-do-computador.jpg";

/**
 * Foto do computador num slot da página.
 *
 * O picker já subia o arquivo, mas o card V2 exigia um `PdvPhoto` e descartava
 * a chave em silêncio — o usuário escolhia a foto e nada acontecia.
 */
describe("book.uploadSlotPhoto", () => {
  let orgA: Organization;
  let orgB: Organization;
  let userA: User;
  let storeA: Store;
  let bookId: string;
  let autoPageId: string;
  let paginaDaOutraOrg: string;
  let paginaExtra: string;

  beforeAll(async () => {
    await resetDb();

    orgA = await createOrg("Rede A");
    orgB = await createOrg("Rede B");
    userA = await createUser();
    await createMember(userA, orgA);
    const userB = await createUser();

    storeA = await prisma.store.create({
      data: { organizationId: orgA.id, name: "Loja A" },
    });

    const book = await prisma.book.create({
      data: {
        organizationId: orgA.id,
        name: "Book de agosto",
        periodMonth: 8,
        periodYear: 2026,
        createdById: userA.id,
      },
      select: { id: true },
    });
    bookId = book.id;

    // Página AUTO: é a que o resyncBook apaga e recria.
    autoPageId = (
      await prisma.bookPage.create({
        data: {
          bookId,
          order: 0,
          storeId: storeA.id,
          autoGenerated: true,
        },
        select: { id: true },
      })
    ).id;

    // Página extra (sem loja) — não tem slot de foto.
    paginaExtra = (
      await prisma.bookPage.create({
        data: { bookId, order: 1, storeId: null },
        select: { id: true },
      })
    ).id;

    const outroBook = await prisma.book.create({
      data: {
        organizationId: orgB.id,
        name: "Book da outra rede",
        periodMonth: 8,
        periodYear: 2026,
        createdById: userB.id,
      },
      select: { id: true },
    });
    const storeB = await prisma.store.create({
      data: { organizationId: orgB.id, name: "Loja B" },
    });
    paginaDaOutraOrg = (
      await prisma.bookPage.create({
        data: { bookId: outroBook.id, order: 0, storeId: storeB.id },
        select: { id: true },
      })
    ).id;
  });

  afterAll(resetDb);

  const ctx = () => ({ context: s2sContext(userA, orgA) });

  // A regra mais frágil do projeto: o escopo por org é manual em cada handler.
  it("não deixa a org A subir foto numa página da org B", async () => {
    await expect(
      call(
        uploadSlotPhoto,
        { bookPageId: paginaDaOutraOrg, slotIndex: 0, photoKey: KEY },
        ctx(),
      ),
    ).rejects.toThrow(/não encontrada/i);

    expect(
      await prisma.pdvPhoto.count({ where: { photos: { has: KEY } } }),
    ).toBe(0);
  });

  it("recusa página extra, que não tem slot de foto", async () => {
    await expect(
      call(
        uploadSlotPhoto,
        { bookPageId: paginaExtra, slotIndex: 0, photoKey: KEY },
        ctx(),
      ),
    ).rejects.toThrow(/extra/i);
  });

  it("cria o PdvPhoto na loja da página e ocupa o slot", async () => {
    const result = await call(
      uploadSlotPhoto,
      { bookPageId: autoPageId, slotIndex: 0, photoKey: KEY },
      ctx(),
    );

    const photo = await prisma.pdvPhoto.findUniqueOrThrow({
      where: { id: result.pdvPhotoId },
      select: {
        organizationId: true,
        storeId: true,
        photos: true,
        supplierId: true,
        promoterName: true,
        submittedAt: true,
      },
    });
    expect(photo.organizationId).toBe(orgA.id);
    expect(photo.storeId).toBe(storeA.id);
    expect(photo.photos).toEqual([KEY]);
    // Sem promotor nem envio: fica fora da fila de aprovação e do picker de
    // fotos aprovadas, que filtram por esses campos.
    expect(photo.promoterName).toBeNull();
    expect(photo.submittedAt).toBeNull();
    expect(photo.supplierId).toBeNull();

    const item = await prisma.bookItem.findUniqueOrThrow({
      where: { id: result.itemId },
      select: { bookId: true, bookPageId: true, slotIndex: true },
    });
    expect(item).toEqual({
      bookId,
      bookPageId: autoPageId,
      slotIndex: 0,
    });
  });

  // Sem isto a foto do computador some no primeiro resync: ela não está no
  // acervo aprovado de onde o resync remonta as páginas AUTO.
  it("tira a página do modo automático", async () => {
    const page = await prisma.bookPage.findUniqueOrThrow({
      where: { id: autoPageId },
      select: { autoGenerated: true },
    });
    expect(page.autoGenerated).toBe(false);
  });

  it("subir de novo no mesmo slot troca a foto, sem duplicar o item", async () => {
    const antes = await prisma.bookItem.count({
      where: { bookPageId: autoPageId },
    });

    const result = await call(
      uploadSlotPhoto,
      { bookPageId: autoPageId, slotIndex: 0, photoKey: "books/outra.jpg" },
      ctx(),
    );

    expect(
      await prisma.bookItem.count({ where: { bookPageId: autoPageId } }),
    ).toBe(antes);
    const item = await prisma.bookItem.findUniqueOrThrow({
      where: { id: result.itemId },
      select: { pdvPhotoId: true },
    });
    expect(item.pdvPhotoId).toBe(result.pdvPhotoId);
  });

  // O helper de slot é compartilhado pelos dois caminhos: se divergirem, o
  // @@unique([bookPageId, slotIndex]) quebra em produção, não aqui.
  it("setSlotPhoto continua ocupando o mesmo slot pelo helper compartilhado", async () => {
    const doAcervo = await prisma.pdvPhoto.create({
      data: {
        organizationId: orgA.id,
        storeId: storeA.id,
        photos: ["books/do-acervo.jpg"],
        createdById: userA.id,
      },
      select: { id: true },
    });

    const result = await call(
      setSlotPhoto,
      { bookPageId: autoPageId, slotIndex: 0, pdvPhotoId: doAcervo.id },
      ctx(),
    );

    const item = await prisma.bookItem.findUniqueOrThrow({
      where: { id: result.itemId },
      select: { pdvPhotoId: true, slotIndex: true },
    });
    expect(item).toEqual({ pdvPhotoId: doAcervo.id, slotIndex: 0 });
  });
});
