"use client";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { constructUrl } from "@/hooks/use-construct-url";
import { ChevronDown, ChevronUp, Crop, Trash2 } from "lucide-react";
import { useState } from "react";
import {
  useDeleteBookPage,
  useRemoveBookItem,
  useSetSlotAdjustment,
  useSetSlotPhoto,
} from "../../hooks/use-books";
import type { BookVariableValues } from "../../lib/book-variables";
import {
  DEFAULT_PHOTO_ADJUSTMENT,
  type PhotoAdjustment,
} from "../../lib/photo-adjustment";
import { ImportPhotoDialog } from "./import-photo-dialog";
import { PhotoAdjustDialog } from "./photo-adjust-dialog";
import { LayoutPreview, type LayoutLogos } from "../templates/layout-preview";
import { TradegramMark } from "../tradegram-mark";
import { useApprovedForImport } from "@/features/promotor/hooks/use-promotor";

// Item de uma página de book no NOVO modelo (BookPage): 1..4 fotos, cada
// uma vinda de um BookItem cujo pdvPhotoId aponta pra uma captura aprovada
// distinta. As ações: trocar foto, ajustar enquadramento, excluir foto,
// excluir página inteira.
export interface BookPageItemV2 {
  id: string; // BookItem.id
  pdvPhotoId: string;
  slotIndex: number;
  photoKey: string | null;
  // Enquadramento salvo (pan/zoom/fit/backdrop), JSON cru vindo do get.ts.
  adjustment?: unknown;
  // Dados da captura desta foto (pra variáveis "por foto" quando um texto a
  // referencia).
  capturedCity?: string | null;
  capturedState?: string | null;
  promoterName?: string | null;
}

export interface BookPageV2 {
  id: string; // BookPage.id
  storeId: string | null;
  // Página extra (sem loja): só layout, sem fotos.
  isExtra?: boolean;
  storeName: string | null;
  storeCity?: string | null;
  storeState?: string | null;
  order: number;
  autoGenerated: boolean;
  // Layout do padrão da indústria aplicado a esta página (logos, nome da loja,
  // fundo, arranjo dos slots). JSON cru — pode ser null em páginas manuais sem
  // padrão, quando caímos numa grade simples.
  pageLayout?: unknown;
  pageBackground?: unknown;
  items: BookPageItemV2[];
}

interface BookPageCardV2Props {
  bookId: string;
  supplierId: string | null;
  page: BookPageV2;
  position: number;
  total: number;
  logos: LayoutLogos;
  variableValues: BookVariableValues;
  // Número sequencial de cada foto no book (slotIndex → N), pra legenda "FOTO N".
  photoNumbers: Record<number, number>;
  onMoveUp: () => void;
  onMoveDown: () => void;
  canMoveUp: boolean;
  canMoveDown: boolean;
}

export function BookPageCardV2({
  bookId,
  supplierId,
  page,
  position,
  total,
  logos,
  variableValues,
  photoNumbers,
  onMoveUp,
  onMoveDown,
  canMoveUp,
  canMoveDown,
}: BookPageCardV2Props) {
  const removeItem = useRemoveBookItem();
  const deletePage = useDeleteBookPage();
  const setSlot = useSetSlotPhoto();
  const setAdjustment = useSetSlotAdjustment();
  const [swapContext, setSwapContext] = useState<{
    slotIndex: number;
    itemId: string | null;
  } | null>(null);
  const [adjustItem, setAdjustItem] = useState<BookPageItemV2 | null>(null);

  // Quantos slots a página tem: o maior entre nº de items e (maior slotIndex+1),
  // pra cobrir slots vazios no meio.
  const maxSlotIndex = page.items.reduce(
    (max, it) => Math.max(max, it.slotIndex),
    -1,
  );
  const slotCount = Math.max(page.items.length, maxSlotIndex + 1, 1);
  const itemBySlot = (i: number) =>
    page.items.find((it) => it.slotIndex === i) ?? null;

  // Layout do padrão desta página, se houver. Sem ele (página manual antiga),
  // cai numa grade simples.
  const hasLayout = Array.isArray(page.pageLayout);

  // Arrays indexados por slotIndex pro LayoutPreview resolver cada foto no seu
  // espaço do padrão.
  const photoUrls: string[] = [];
  const photoAdjustments: Array<PhotoAdjustment | undefined> = [];
  for (let i = 0; i < slotCount; i++) {
    const item = itemBySlot(i);
    photoUrls[i] = item?.photoKey ? constructUrl(item.photoKey) : "";
    photoAdjustments[i] = parseAdjustment(item?.adjustment);
  }

  // Loja/cidade/UF preenchem as variáveis por página; as demais vêm do book.
  const pageVariables: BookVariableValues = {
    ...variableValues,
    loja: page.storeName,
    cidade: page.storeCity ?? null,
    uf: page.storeState ?? null,
  };

  // Variáveis "por foto" (quando um texto do padrão referencia uma foto):
  // cidade/UF da loja, com fallback pra captura; número e promotor da foto.
  const photoVariables: Record<number, BookVariableValues> = {};
  for (const item of page.items) {
    const n = photoNumbers[item.slotIndex];
    photoVariables[item.slotIndex] = {
      numeroFoto: n != null ? String(n) : null,
      cidade: page.storeCity ?? item.capturedCity ?? null,
      uf: page.storeState ?? item.capturedState ?? null,
      promotor: item.promoterName ?? null,
    };
  }

  const removePage = () => deletePage.mutate({ bookId, pageId: page.id });

  const isBusy =
    removeItem.isPending || setSlot.isPending || deletePage.isPending;

  return (
    <Card className="overflow-hidden">
      <div className="flex items-center justify-between border-b bg-muted/30 px-4 py-2">
        <div className="flex items-center gap-2 text-sm">
          <span className="font-semibold">
            Página {position}/{total}
          </span>
          <span className="text-muted-foreground">·</span>
          {page.isExtra ? (
            <Badge variant="outline">Página extra</Badge>
          ) : (
            <span className="font-medium">{page.storeName}</span>
          )}
          {page.autoGenerated && (
            <Badge variant="secondary" className="ml-1">
              auto
            </Badge>
          )}
        </div>
        <div className="flex items-center gap-1">
          <Button
            type="button"
            variant="ghost"
            size="icon"
            className="size-8"
            onClick={onMoveUp}
            disabled={!canMoveUp || isBusy}
            title="Mover para cima"
          >
            <ChevronUp className="size-4" />
          </Button>
          <Button
            type="button"
            variant="ghost"
            size="icon"
            className="size-8"
            onClick={onMoveDown}
            disabled={!canMoveDown || isBusy}
            title="Mover para baixo"
          >
            <ChevronDown className="size-4" />
          </Button>
          <Button
            type="button"
            variant="ghost"
            size="sm"
            onClick={removePage}
            disabled={deletePage.isPending}
            className="text-destructive hover:text-destructive"
          >
            <Trash2 className="size-4" />
            Excluir página
          </Button>
        </div>
      </div>

      <CardContent className="space-y-3 p-4">
        <div className="relative">
          {hasLayout ? (
            <LayoutPreview
              layout={page.pageLayout}
              background={page.pageBackground}
              photoUrls={photoUrls}
              photoAdjustments={photoAdjustments}
              photoNumbers={photoNumbers}
              variableValues={pageVariables}
              photoVariables={photoVariables}
              logos={logos}
              className="rounded-md border"
              onSlotClick={(slotIndex) =>
                setSwapContext({
                  slotIndex,
                  itemId: itemBySlot(slotIndex)?.id ?? null,
                })
              }
            />
          ) : (
            <SimpleGrid
              slotCount={slotCount}
              itemBySlot={itemBySlot}
              onSwap={(slotIndex) =>
                setSwapContext({
                  slotIndex,
                  itemId: itemBySlot(slotIndex)?.id ?? null,
                })
              }
            />
          )}
          <TradegramMark />
        </div>

        {/* Barra de ações por foto: clicar no slot troca a foto; aqui ficam
            Ajustar (reenquadrar) e Remover, que precisam de alvo explícito.
            Páginas extras não têm fotos — nada a mostrar. */}
        {!page.isExtra && (
          <div className="flex flex-wrap items-center gap-2">
            <span className="text-xs text-muted-foreground">
              Clique numa foto para trocá-la.
            </span>
            {Array.from({ length: slotCount }, (_, i) => itemBySlot(i))
              .filter((it): it is BookPageItemV2 => !!it?.photoKey)
              .map((it) => (
                <div
                  key={it.id}
                  className="flex items-center gap-0.5 rounded-md border bg-muted/40 px-1.5 py-0.5 text-xs"
                >
                  <span className="px-1 font-medium">
                    Foto {it.slotIndex + 1}
                  </span>
                  <Button
                    type="button"
                    variant="ghost"
                    size="sm"
                    className="h-6 gap-1 px-1.5"
                    onClick={() => setAdjustItem(it)}
                    disabled={isBusy}
                  >
                    <Crop className="size-3" />
                    Ajustar
                  </Button>
                  <Button
                    type="button"
                    variant="ghost"
                    size="sm"
                    className="h-6 gap-1 px-1.5 text-destructive hover:text-destructive"
                    onClick={() => removeItem.mutate({ bookId, itemId: it.id })}
                    disabled={isBusy}
                  >
                    <Trash2 className="size-3" />
                    Remover
                  </Button>
                </div>
              ))}
          </div>
        )}
      </CardContent>

      {swapContext !== null && (
        <SwapPhotoDialog
          open
          onOpenChange={(open) => !open && setSwapContext(null)}
          supplierId={supplierId}
          supplierName={
            typeof variableValues.industria === "string"
              ? variableValues.industria
              : null
          }
          storeId={page.storeId ?? ""}
          storeName={page.storeName}
          onPickPdvPhoto={(pdvPhotoId) => {
            setSlot.mutate(
              {
                bookPageId: page.id,
                slotIndex: swapContext.slotIndex,
                pdvPhotoId,
              },
              { onSuccess: () => setSwapContext(null) },
            );
          }}
        />
      )}

      {adjustItem?.photoKey && (
        <PhotoAdjustDialog
          open
          onOpenChange={(open) => !open && setAdjustItem(null)}
          photoUrl={constructUrl(adjustItem.photoKey)}
          aspectRatio={16 / 9}
          allowFit
          initialAdjustment={parseAdjustment(adjustItem.adjustment)}
          onSave={(adjustment) => {
            if (!adjustItem.photoKey) return;
            setAdjustment.mutate(
              {
                pdvPhotoId: adjustItem.pdvPhotoId,
                photoKey: adjustItem.photoKey,
                adjustment,
              },
              { onSuccess: () => setAdjustItem(null) },
            );
          }}
        />
      )}
    </Card>
  );
}

// Fallback pra páginas sem padrão montado (manuais antigas): grade simples de
// fotos, clicável pra trocar.
function SimpleGrid({
  slotCount,
  itemBySlot,
  onSwap,
}: {
  slotCount: number;
  itemBySlot: (i: number) => BookPageItemV2 | null;
  onSwap: (slotIndex: number) => void;
}) {
  return (
    <div
      className={
        slotCount === 1 ? "grid grid-cols-1 gap-2" : "grid grid-cols-2 gap-2"
      }
      style={{ aspectRatio: "16 / 9" }}
    >
      {Array.from({ length: slotCount }, (_, i) => {
        const item = itemBySlot(i);
        return (
          <button
            type="button"
            key={i}
            onClick={() => onSwap(i)}
            className="group relative overflow-hidden rounded-md border bg-muted"
          >
            {item?.photoKey ? (
              // biome-ignore lint/performance/noImgElement: thumbnail do R2 pré-assinada
              <img
                src={constructUrl(item.photoKey)}
                alt=""
                loading="lazy"
                className="size-full object-cover"
              />
            ) : (
              <div className="flex size-full items-center justify-center text-xs text-muted-foreground">
                + Foto
              </div>
            )}
          </button>
        );
      })}
    </div>
  );
}

// Converte o JSON cru de get.ts num PhotoAdjustment tipado (ou undefined).
function parseAdjustment(raw: unknown): PhotoAdjustment | undefined {
  if (!raw || typeof raw !== "object") return undefined;
  const a = raw as Record<string, unknown>;
  if (typeof a.zoom !== "number") return undefined;
  return {
    ...DEFAULT_PHOTO_ADJUSTMENT,
    ...(a as unknown as PhotoAdjustment),
  };
}

// Wrapper que traduz o photoKey retornado pelo ImportPhotoDialog em
// pdvPhotoId (o modelo novo salva relação, não string). Usa a mesma query
// que o dialog já usou pra listar fotos aprovadas — o cliente já cacheou.
function SwapPhotoDialog({
  open,
  onOpenChange,
  supplierId,
  supplierName,
  storeId,
  storeName,
  onPickPdvPhoto,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  supplierId: string | null;
  supplierName: string | null;
  storeId: string;
  storeName: string | null;
  onPickPdvPhoto: (pdvPhotoId: string) => void;
}) {
  const { photos } = useApprovedForImport(
    storeId,
    supplierId ?? undefined,
    open,
  );

  return (
    <ImportPhotoDialog
      open={open}
      onOpenChange={onOpenChange}
      defaultSupplierId={supplierId}
      defaultSupplierName={supplierName}
      defaultStoreId={storeId || null}
      defaultStoreName={storeName}
      lockSelection
      onPick={(photoKey) => {
        // Encontra o PdvPhoto correspondente à photoKey escolhida. Se o usuário
        // subiu uma foto nova (upload direto), não vai bater com nenhum
        // approvedForImport — nesse caso silenciamos: a troca por upload
        // externo fica pra futura iteração (envolve criar PdvPhoto novo).
        const match = photos.find((p) => p.photoKey === photoKey);
        if (match) onPickPdvPhoto(match.id);
      }}
    />
  );
}
