"use client";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuSub,
  DropdownMenuSubContent,
  DropdownMenuSubTrigger,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { constructUrl } from "@/hooks/use-construct-url";
import {
  ChevronDown,
  ChevronUp,
  Crop,
  Images,
  LayoutTemplate,
  Maximize2,
  MoreHorizontal,
  Pencil,
  Plus,
  Trash2,
} from "lucide-react";
import { type ReactNode, useState } from "react";
import {
  useChangeBookPageLayout,
  useDeleteBookPage,
  useRemoveBookItem,
  useSetSlotAdjustment,
  useSetSlotPhoto,
  useUploadSlotPhoto,
} from "../../hooks/use-books";
import type { BookVariableValues } from "../../lib/book-variables";
import {
  DEFAULT_PHOTO_ADJUSTMENT,
  type PhotoAdjustment,
} from "../../lib/photo-adjustment";
import { BookPageLayoutDialog } from "./book-page-layout-dialog";
import { BookStorePhotosDialog } from "./book-store-photos-dialog";
import { HoverZoom } from "./hover-zoom";
import { ImportPhotoDialog } from "./import-photo-dialog";
import { PhotoAdjustDialog } from "./photo-adjust-dialog";
import { LayoutPreview, type LayoutLogos } from "../templates/layout-preview";
import { TradegramMark } from "../tradegram-mark";

// Item de uma página de book no NOVO modelo (BookPage): 1..4 fotos, cada
// uma vinda de um BookItem cujo pdvPhotoId aponta pra uma captura aprovada
// distinta. As ações: trocar foto, ajustar enquadramento, excluir foto,
// excluir página inteira.
// Os 5 padrões de página (orientação + nº de slots). "Alterar padrão da página"
// mostra todos menos o atual.
const PAGE_PATTERNS = [
  { orientation: "PORTRAIT", size: 1, label: "1 foto vertical" },
  { orientation: "PORTRAIT", size: 2, label: "2 fotos verticais" },
  { orientation: "PORTRAIT", size: 3, label: "3 fotos verticais" },
  { orientation: "LANDSCAPE", size: 1, label: "1 foto horizontal" },
  { orientation: "LANDSCAPE", size: 2, label: "2 fotos horizontais" },
] as const;

// Padrão atual da página, inferido dos slots do layout (largura ≥ altura =
// horizontal). Usado só pra ocultar a opção atual no menu.
function inferCurrentPattern(
  layout: unknown,
): { orientation: "PORTRAIT" | "LANDSCAPE"; size: number } | null {
  if (!Array.isArray(layout)) return null;
  const slots = (
    layout as Array<{ type?: string; width?: number; height?: number }>
  ).filter((el) => el?.type === "photoSlot");
  if (slots.length === 0) return null;
  const first = slots[0];
  return {
    orientation:
      (first.width ?? 0) >= (first.height ?? 0) ? "LANDSCAPE" : "PORTRAIT",
    size: slots.length,
  };
}

export interface BookPageItemV2 {
  id: string; // BookItem.id
  pdvPhotoId: string;
  slotIndex: number;
  photoKey: string | null;
  // Enquadramento salvo (pan/zoom/fit/backdrop), JSON cru vindo do get.ts.
  adjustment?: unknown;
  // Dados da captura desta foto (pra variáveis "por foto" quando um texto a
  // referencia).
  capturedCity?: string | null;
  capturedState?: string | null;
  promoterName?: string | null;
}

export interface BookPageV2 {
  id: string; // BookPage.id
  storeId: string | null;
  // Página extra (sem loja): só layout, sem fotos.
  isExtra?: boolean;
  storeName: string | null;
  storeCity?: string | null;
  storeState?: string | null;
  order: number;
  autoGenerated: boolean;
  // Layout do padrão da indústria aplicado a esta página (logos, nome da loja,
  // fundo, arranjo dos slots). JSON cru — pode ser null em páginas manuais sem
  // padrão, quando caímos numa grade simples.
  pageLayout?: unknown;
  pageBackground?: unknown;
  items: BookPageItemV2[];
}

interface BookPageCardV2Props {
  bookId: string;
  supplierId: string | null;
  page: BookPageV2;
  position: number;
  total: number;
  logos: LayoutLogos;
  variableValues: BookVariableValues;
  // Número sequencial de cada foto no book (slotIndex → N), pra legenda "FOTO N".
  photoNumbers: Record<number, number>;
  // Interruptor "Numerar as fotos" do book.
  showPhotoNumbers: boolean;
  onMoveUp: () => void;
  onMoveDown: () => void;
  onInsertAfter: () => void;
  canMoveUp: boolean;
  canMoveDown: boolean;
}

export function BookPageCardV2({
  bookId,
  supplierId,
  page,
  position,
  total,
  logos,
  variableValues,
  photoNumbers,
  showPhotoNumbers,
  onMoveUp,
  onMoveDown,
  onInsertAfter,
  canMoveUp,
  canMoveDown,
}: BookPageCardV2Props) {
  const removeItem = useRemoveBookItem();
  const deletePage = useDeleteBookPage();
  const setSlot = useSetSlotPhoto();
  const uploadSlot = useUploadSlotPhoto();
  const setAdjustment = useSetSlotAdjustment();
  const changePattern = useChangeBookPageLayout();
  const currentPattern = inferCurrentPattern(page.pageLayout);
  const [swapContext, setSwapContext] = useState<{
    slotIndex: number;
    itemId: string | null;
  } | null>(null);
  const [adjustItem, setAdjustItem] = useState<BookPageItemV2 | null>(null);
  const [layoutOpen, setLayoutOpen] = useState(false);
  const [storePhotosOpen, setStorePhotosOpen] = useState(false);

  // Quantos slots a página tem: o maior entre nº de items e (maior slotIndex+1),
  // pra cobrir slots vazios no meio.
  const maxSlotIndex = page.items.reduce(
    (max, it) => Math.max(max, it.slotIndex),
    -1,
  );
  const slotCount = Math.max(page.items.length, maxSlotIndex + 1, 1);
  const itemBySlot = (i: number) =>
    page.items.find((it) => it.slotIndex === i) ?? null;

  // Layout do padrão desta página, se houver. Sem ele (página manual antiga),
  // cai numa grade simples.
  const hasLayout = Array.isArray(page.pageLayout);

  // Arrays indexados por slotIndex pro LayoutPreview resolver cada foto no seu
  // espaço do padrão.
  const photoUrls: string[] = [];
  const photoAdjustments: Array<PhotoAdjustment | undefined> = [];
  for (let i = 0; i < slotCount; i++) {
    const item = itemBySlot(i);
    photoUrls[i] = item?.photoKey ? constructUrl(item.photoKey) : "";
    photoAdjustments[i] = parseAdjustment(item?.adjustment);
  }

  // Loja/cidade/UF preenchem as variáveis por página; as demais vêm do book.
  const pageVariables: BookVariableValues = {
    ...variableValues,
    loja: page.storeName,
    cidade: page.storeCity ?? null,
    uf: page.storeState ?? null,
  };

  // Variáveis "por foto" (quando um texto do padrão referencia uma foto):
  // cidade/UF da loja, com fallback pra captura; número e promotor da foto.
  const photoVariables: Record<number, BookVariableValues> = {};
  for (const item of page.items) {
    const n = photoNumbers[item.slotIndex];
    photoVariables[item.slotIndex] = {
      numeroFoto: n != null ? String(n) : null,
      cidade: page.storeCity ?? item.capturedCity ?? null,
      uf: page.storeState ?? item.capturedState ?? null,
      promotor: item.promoterName ?? null,
    };
  }

  const removePage = () => deletePage.mutate({ bookId, pageId: page.id });

  // "Caber inteira" da página: enquadra TODAS as fotos em contain (foto inteira,
  // sem corte) de uma vez — o ajuste é por foto (photoAdjustments), então dispara
  // uma mutação por item preservando pan/zoom/backdrop.
  const hasPhotos = page.items.some((it) => it.photoKey);
  const fitAllContain = () => {
    for (const item of page.items) {
      if (!item.photoKey) continue;
      const current =
        parseAdjustment(item.adjustment) ?? DEFAULT_PHOTO_ADJUSTMENT;
      setAdjustment.mutate({
        pdvPhotoId: item.pdvPhotoId,
        photoKey: item.photoKey,
        adjustment: { ...current, objectFit: "contain" },
      });
    }
  };

  const isBusy =
    removeItem.isPending || setSlot.isPending || deletePage.isPending;

  return (
    /* Sem moldura: a única coisa que aparece na mesa é a própria página — o
       cartão e o cabeçalho ficam transparentes sobre o cinza. */
    <Card className="gap-0 overflow-hidden border-0 bg-transparent py-0 shadow-none">
      <div className="flex items-center justify-between px-1 py-2">
        <div className="flex items-center gap-2 text-sm">
          <span className="font-semibold">
            Página {position}/{total}
          </span>
          <span className="text-muted-foreground">·</span>
          {page.isExtra ? (
            <Badge variant="outline">Página extra</Badge>
          ) : (
            <span className="font-medium">{page.storeName}</span>
          )}
          {page.autoGenerated && (
            <Badge variant="secondary" className="ml-1">
              auto
            </Badge>
          )}
        </div>
        {/* Uma ação em destaque (editar layout), mover, e todo o resto num
            menu só: com 11 páginas na tela, sete botões por cabeçalho viravam
            ruído antes de virar atalho. */}
        <div className="flex items-center gap-1">
          <Button
            type="button"
            variant="outline"
            size="sm"
            className="gap-1"
            onClick={() => setLayoutOpen(true)}
            title="Editar o layout desta página (fundo, imagens, textos)"
          >
            <Pencil className="size-4" />
            Editar layout
          </Button>
          <Button
            type="button"
            variant="ghost"
            size="icon"
            className="size-8"
            onClick={onMoveUp}
            disabled={!canMoveUp || isBusy}
            title="Mover para cima"
          >
            <ChevronUp className="size-4" />
          </Button>
          <Button
            type="button"
            variant="ghost"
            size="icon"
            className="size-8"
            onClick={onMoveDown}
            disabled={!canMoveDown || isBusy}
            title="Mover para baixo"
          >
            <ChevronDown className="size-4" />
          </Button>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button
                type="button"
                variant="ghost"
                size="icon"
                className="size-8"
                disabled={isBusy}
                title="Mais ações desta página"
                aria-label={`Mais ações da página ${position}`}
              >
                <MoreHorizontal className="size-4" />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuLabel>Página {position}</DropdownMenuLabel>
              {hasPhotos && (
                <DropdownMenuItem
                  onClick={fitAllContain}
                  disabled={setAdjustment.isPending || isBusy}
                >
                  <Maximize2 className="size-4" />
                  Caber inteira (todas as fotos)
                </DropdownMenuItem>
              )}
              {!page.isExtra && page.storeId && (
                <DropdownMenuItem onClick={() => setStorePhotosOpen(true)}>
                  <Images className="size-4" />
                  Fotos desta loja
                </DropdownMenuItem>
              )}
              {!page.isExtra && (
                <DropdownMenuSub>
                  <DropdownMenuSubTrigger>
                    <LayoutTemplate className="size-4" />
                    Alterar padrão da página
                  </DropdownMenuSubTrigger>
                  <DropdownMenuSubContent>
                    {PAGE_PATTERNS.filter(
                      (p) =>
                        !currentPattern ||
                        p.orientation !== currentPattern.orientation ||
                        p.size !== currentPattern.size,
                    ).map((p) => (
                      <DropdownMenuItem
                        key={`${p.orientation}-${p.size}`}
                        disabled={changePattern.isPending}
                        onClick={() =>
                          changePattern.mutate({
                            bookPageId: page.id,
                            orientation: p.orientation,
                            size: p.size,
                          })
                        }
                      >
                        {p.label}
                      </DropdownMenuItem>
                    ))}
                  </DropdownMenuSubContent>
                </DropdownMenuSub>
              )}
              <DropdownMenuItem onClick={onInsertAfter}>
                <Plus className="size-4" />
                Inserir página depois desta
              </DropdownMenuItem>
              <DropdownMenuSeparator />
              <DropdownMenuItem
                variant="destructive"
                onClick={removePage}
                disabled={deletePage.isPending}
              >
                <Trash2 className="size-4" />
                Excluir página
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      </div>

      <CardContent className="px-0 pb-0">
        {/* Clicar em QUALQUER parte da página que não seja uma foto abre o
            editor de layout — fundo, textos e logos se editam lá. As fotos têm
            ação própria (trocar) e param o clique antes de chegar aqui.
            O caminho de teclado é o botão "Editar layout" do cabeçalho, por
            isso este container não vira alvo focável (botão dentro de botão). */}
        {/* biome-ignore lint/a11y/noStaticElementInteractions: atalho de mouse; o teclado usa o botão "Editar layout" do cabeçalho */}
        {/* biome-ignore lint/a11y/useKeyWithClickEvents: idem — a ação já tem botão próprio, acessível por teclado */}
        <div
          className="group relative cursor-pointer"
          onClick={() => setLayoutOpen(true)}
        >
          <HoverZoom>
            {hasLayout ? (
              <LayoutPreview
                layout={page.pageLayout}
                background={page.pageBackground}
                photoUrls={photoUrls}
                photoAdjustments={photoAdjustments}
                photoNumbers={photoNumbers}
                showPhotoNumbers={showPhotoNumbers}
                variableValues={pageVariables}
                photoVariables={photoVariables}
                logos={logos}
                className="rounded-md shadow-sm"
                onSlotClick={(slotIndex) =>
                  setSwapContext({
                    slotIndex,
                    itemId: itemBySlot(slotIndex)?.id ?? null,
                  })
                }
                slotOverlay={(slotIndex, hasPhoto) => (
                  <PhotoControls
                    item={hasPhoto ? itemBySlot(slotIndex) : null}
                    disabled={isBusy}
                    onAdjust={setAdjustItem}
                    onRemove={(itemId) => removeItem.mutate({ bookId, itemId })}
                  />
                )}
              />
            ) : (
              <SimpleGrid
                slotCount={slotCount}
                itemBySlot={itemBySlot}
                onSwap={(slotIndex) =>
                  setSwapContext({
                    slotIndex,
                    itemId: itemBySlot(slotIndex)?.id ?? null,
                  })
                }
                slotOverlay={(slotIndex) => (
                  <PhotoControls
                    item={itemBySlot(slotIndex)}
                    disabled={isBusy}
                    onAdjust={setAdjustItem}
                    onRemove={(itemId) => removeItem.mutate({ bookId, itemId })}
                  />
                )}
              />
            )}
          </HoverZoom>
          <TradegramMark />
        </div>
      </CardContent>

      {swapContext !== null && (
        <SwapPhotoDialog
          open
          onOpenChange={(open) => !open && setSwapContext(null)}
          bookId={bookId}
          supplierId={supplierId}
          storeId={page.storeId ?? ""}
          storeName={page.storeName}
          onPickPdvPhoto={(pdvPhotoId) => {
            setSlot.mutate(
              {
                bookPageId: page.id,
                slotIndex: swapContext.slotIndex,
                pdvPhotoId,
              },
              { onSuccess: () => setSwapContext(null) },
            );
          }}
          onPickUpload={(photoKey) => {
            uploadSlot.mutate(
              {
                bookPageId: page.id,
                slotIndex: swapContext.slotIndex,
                photoKey,
              },
              { onSuccess: () => setSwapContext(null) },
            );
          }}
        />
      )}

      {adjustItem?.photoKey && (
        <PhotoAdjustDialog
          open
          onOpenChange={(open) => !open && setAdjustItem(null)}
          photoUrl={constructUrl(adjustItem.photoKey)}
          aspectRatio={16 / 9}
          allowFit
          initialAdjustment={parseAdjustment(adjustItem.adjustment)}
          onSave={(adjustment) => {
            if (!adjustItem.photoKey) return;
            setAdjustment.mutate(
              {
                pdvPhotoId: adjustItem.pdvPhotoId,
                photoKey: adjustItem.photoKey,
                adjustment,
              },
              { onSuccess: () => setAdjustItem(null) },
            );
          }}
        />
      )}

      <BookPageLayoutDialog
        open={layoutOpen}
        onOpenChange={setLayoutOpen}
        bookPageId={page.id}
        storeName={page.isExtra ? "Página extra" : (page.storeName ?? "Loja")}
        layout={page.pageLayout}
        background={page.pageBackground}
        variableValues={pageVariables}
        photoPreviewUrls={photoUrls.filter(Boolean)}
        logos={logos}
      />

      {!page.isExtra && page.storeId && (
        <BookStorePhotosDialog
          open={storePhotosOpen}
          onOpenChange={setStorePhotosOpen}
          bookId={bookId}
          storeId={page.storeId}
          supplierId={supplierId}
          storeName={page.storeName ?? "Loja"}
        />
      )}
    </Card>
  );
}

// Fallback pra páginas sem padrão montado (manuais antigas): grade simples de
// fotos, clicável pra trocar.
// Ajustar e remover POR FOTO, no canto superior direito dela. Ficam sobre a
// foto (e não numa barra à parte) pra o alvo ser óbvio quando a página tem
// várias. É DOM do editor: o PDF é montado no servidor a partir do layout
// (react-pdf), então nada disso entra no arquivo.
function PhotoControls({
  item,
  disabled,
  onAdjust,
  onRemove,
}: {
  item: BookPageItemV2 | null;
  disabled: boolean;
  onAdjust: (item: BookPageItemV2) => void;
  onRemove: (itemId: string) => void;
}) {
  if (!item?.photoKey) return null;
  return (
    <div className="pointer-events-auto absolute right-1.5 top-1.5 z-10 flex gap-1 opacity-0 transition-opacity group-hover:opacity-100 focus-within:opacity-100">
      <Button
        type="button"
        variant="secondary"
        size="icon"
        className="size-7 border bg-background/90 shadow-sm backdrop-blur hover:bg-background"
        onClick={(event) => {
          event.stopPropagation();
          onAdjust(item);
        }}
        disabled={disabled}
        title="Ajustar enquadramento"
        aria-label={`Ajustar enquadramento da foto ${item.slotIndex + 1}`}
      >
        <Crop className="size-3.5" />
      </Button>
      <Button
        type="button"
        variant="secondary"
        size="icon"
        className="size-7 border bg-background/90 text-destructive shadow-sm backdrop-blur hover:bg-background hover:text-destructive"
        onClick={(event) => {
          event.stopPropagation();
          onRemove(item.id);
        }}
        disabled={disabled}
        title="Remover foto"
        aria-label={`Remover a foto ${item.slotIndex + 1}`}
      >
        <Trash2 className="size-3.5" />
      </Button>
    </div>
  );
}

function SimpleGrid({
  slotCount,
  itemBySlot,
  onSwap,
  slotOverlay,
}: {
  slotCount: number;
  itemBySlot: (i: number) => BookPageItemV2 | null;
  onSwap: (slotIndex: number) => void;
  slotOverlay?: (slotIndex: number) => ReactNode;
}) {
  return (
    <div
      className={
        slotCount === 1 ? "grid grid-cols-1 gap-2" : "grid grid-cols-2 gap-2"
      }
      style={{ aspectRatio: "16 / 9" }}
    >
      {Array.from({ length: slotCount }, (_, i) => {
        const item = itemBySlot(i);
        // Wrapper em div, não em button: os controles são botões e botão
        // dentro de botão é HTML inválido.
        return (
          <div key={i} className="relative">
            <button
              type="button"
              onClick={() => onSwap(i)}
              className="group size-full overflow-hidden rounded-md border bg-muted"
            >
              {item?.photoKey ? (
                // biome-ignore lint/performance/noImgElement: thumbnail do R2 pré-assinada
                <img
                  src={constructUrl(item.photoKey)}
                  alt=""
                  loading="lazy"
                  className="size-full object-cover"
                />
              ) : (
                <div className="flex size-full items-center justify-center text-xs text-muted-foreground">
                  + Foto
                </div>
              )}
            </button>
            {slotOverlay?.(i)}
          </div>
        );
      })}
    </div>
  );
}

// Converte o JSON cru de get.ts num PhotoAdjustment tipado (ou undefined).
function parseAdjustment(raw: unknown): PhotoAdjustment | undefined {
  if (!raw || typeof raw !== "object") return undefined;
  const a = raw as Record<string, unknown>;
  if (typeof a.zoom !== "number") return undefined;
  return {
    ...DEFAULT_PHOTO_ADJUSTMENT,
    ...(a as unknown as PhotoAdjustment),
  };
}

// Wrapper do picker pro slot V2: o ImportPhotoDialog já devolve o pdvPhotoId
// (id) da foto escolhida — mesmo de outra loja ("Todas as lojas"). Upload
// direto vem com id null e fica pra futura iteração (criar PdvPhoto novo).
function SwapPhotoDialog({
  open,
  onOpenChange,
  bookId,
  supplierId,
  storeId,
  storeName,
  onPickPdvPhoto,
  onPickUpload,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  bookId: string;
  supplierId: string | null;
  storeId: string;
  storeName: string | null;
  onPickPdvPhoto: (pdvPhotoId: string) => void;
  // Foto vinda do computador: o arquivo já subiu, só existe a chave R2.
  onPickUpload: (photoKey: string) => void;
}) {
  return (
    <ImportPhotoDialog
      open={open}
      onOpenChange={onOpenChange}
      bookId={bookId}
      defaultSupplierId={supplierId}
      defaultStoreId={storeId || null}
      defaultStoreName={storeName}
      onPick={(photo) => {
        if (photo.id) onPickPdvPhoto(photo.id);
        else onPickUpload(photo.photoKey);
      }}
    />
  );
}
