import { requireAuthMiddleware } from "@/app/middlewares/auth";
import { base } from "@/app/middlewares/base";
import { requireOrgMiddleware } from "@/app/middlewares/org";
import { Prisma } from "@/generated/prisma/client";
import prisma from "@/lib/db";
import { z } from "zod";

// Adiciona uma PÁGINA EXTRA ao book a partir de um padrão kind=EXTRA da
// indústria. A página nasce sem loja e sem fotos — só o layout copiado do
// padrão (abertura/divisória/encerramento). A posição é escolhida via
// `afterPageId`: omitido = no fim; null = no início; um id = logo depois dele.
// Insere renumerando `order` de todas as páginas (contíguo, sem buracos).
export const addBookExtraPage = base
  .use(requireAuthMiddleware)
  .use(requireOrgMiddleware)
  .input(
    z.object({
      bookId: z.string(),
      templateId: z.string(),
      // Onde inserir: undefined = fim; null = início; id = logo após essa página.
      afterPageId: z.string().nullable().optional(),
    }),
  )
  .output(z.object({ id: z.string() }))
  .handler(async ({ input, context, errors }) => {
    const book = await prisma.book.findFirst({
      where: { id: input.bookId, organizationId: context.org.id },
      select: { id: true, supplierId: true },
    });
    if (!book) {
      throw errors.NOT_FOUND({ message: "Book não encontrado" });
    }

    const template = await prisma.bookPageTemplate.findFirst({
      where: {
        id: input.templateId,
        organizationId: context.org.id,
        // O extra tem que ser da MESMA indústria do book — senão um book da
        // indústria A poderia herdar o chrome/logos da indústria B.
        supplierId: book.supplierId,
        kind: "EXTRA",
        isBase: false,
      },
      select: { layout: true, background: true, supplierId: true },
    });
    if (!template) {
      throw errors.NOT_FOUND({
        message: "Padrão de página extra não encontrado",
      });
    }

    const pages = await prisma.bookPage.findMany({
      where: { bookId: book.id },
      orderBy: { order: "asc" },
      select: { id: true },
    });

    // Índice de inserção: fim (undefined), início (null) ou logo após a página
    // escolhida. Id inexistente cai no fim, sem erro.
    let insertIndex: number;
    if (input.afterPageId === undefined) {
      insertIndex = pages.length;
    } else if (input.afterPageId === null) {
      insertIndex = 0;
    } else {
      const idx = pages.findIndex((p) => p.id === input.afterPageId);
      insertIndex = idx === -1 ? pages.length : idx + 1;
    }

    // Página extra é só layout (texto/logos/fundo). Se o padrão tiver slots de
    // foto embutidos, removemos — a extra não recebe fotos.
    const layout = stripPhotoSlots(template.layout);

    const createdId = await prisma.$transaction(async (tx) => {
      const created = await tx.bookPage.create({
        data: {
          bookId: book.id,
          storeId: null,
          order: pages.length, // provisório; renumeramos abaixo
          autoGenerated: false,
          pageLayout: layout ?? Prisma.DbNull,
          pageBackground: template.background ?? Prisma.DbNull,
        },
        select: { id: true },
      });

      const orderedIds = pages.map((p) => p.id);
      orderedIds.splice(insertIndex, 0, created.id);
      for (let i = 0; i < orderedIds.length; i++) {
        await tx.bookPage.update({
          where: { id: orderedIds[i] },
          data: { order: i },
        });
      }

      return created.id;
    });

    return { id: createdId };
  });

// Remove os elementos de espaço de foto de um layout JSON cru, preservando o
// resto (texto, imagens/logos, formas, divisórias).
function stripPhotoSlots(layout: unknown): Prisma.InputJsonValue | null {
  if (!Array.isArray(layout)) return null;
  const chrome = (layout as Array<Record<string, unknown>>).filter(
    (el) => el?.type !== "photoSlot",
  );
  return chrome as unknown as Prisma.InputJsonValue;
}
