import { requireAuthMiddleware } from "@/app/middlewares/auth";
import { base } from "@/app/middlewares/base";
import { requireOrgMiddleware } from "@/app/middlewares/org";
import prisma from "@/lib/db";
import { z } from "zod";
import { assignSlotPhoto } from "./_slot";

/**
 * Foto vinda do COMPUTADOR para um slot da página (modelo V2).
 *
 * O picker já sabia subir um arquivo pro R2, mas o card V2 só aceitava foto
 * com `PdvPhoto` — o upload era descartado em silêncio. Aqui a chave crua vira
 * um `PdvPhoto` da loja da página (mesmo padrão do `addBookPage`, que também
 * cria um registro "recipiente" sem promotor nem aprovação) e ocupa o slot.
 *
 * Sem `supplierId`, `promoterName` nem `submittedAt`: a foto não veio de campo,
 * então fica fora da fila da coordenadora (`for-approval` exige promotor) e
 * fora do picker de fotos aprovadas (`approved-for-import` idem). Ela existe
 * para este book.
 */
export const uploadSlotPhoto = base
  .use(requireAuthMiddleware)
  .use(requireOrgMiddleware)
  .input(
    z.object({
      bookPageId: z.string(),
      slotIndex: z.number().int().min(0).max(3),
      /** Chave R2 do arquivo que o cliente já subiu. */
      photoKey: z.string().min(1),
    }),
  )
  .output(z.object({ pdvPhotoId: z.string(), itemId: z.string() }))
  .handler(async ({ input, context, errors }) => {
    const page = await prisma.bookPage.findFirst({
      where: { id: input.bookPageId, book: { organizationId: context.org.id } },
      select: { id: true, bookId: true, storeId: true, autoGenerated: true },
    });
    if (!page) throw errors.NOT_FOUND({ message: "Página não encontrada" });

    // `PdvPhoto.storeId` é obrigatório. Páginas extras não têm loja — mas
    // também não têm slot de foto (`addExtraPage` remove todos), então cair
    // aqui significa payload inválido, não um caso a tratar.
    if (!page.storeId) {
      throw errors.BAD_REQUEST({
        message: "Página extra não aceita foto",
      });
    }
    const storeId = page.storeId;

    return prisma.$transaction(async (tx) => {
      const photo = await tx.pdvPhoto.create({
        data: {
          organizationId: context.org.id,
          storeId,
          photos: [input.photoKey],
          createdById: context.user.id,
        },
        select: { id: true },
      });

      const { itemId } = await assignSlotPhoto(tx, {
        bookId: page.bookId,
        bookPageId: page.id,
        slotIndex: input.slotIndex,
        pdvPhotoId: photo.id,
      });

      // A página deixa de ser automática. O `resyncBook` apaga e recria as
      // páginas AUTO a cada aprovação/reprovação do período: uma foto do
      // computador some ali para sempre, porque não está no acervo aprovado de
      // onde o resync remonta as páginas.
      if (page.autoGenerated) {
        await tx.bookPage.update({
          where: { id: page.id },
          data: { autoGenerated: false },
        });
      }

      return { pdvPhotoId: photo.id, itemId };
    });
  });
