-- Auto-geração de books: 1 book = N BookPages (uma loja por página); cada
-- BookPage = 1..4 BookItems (um por slot). BookItems legados (books manuais
-- criados antes desta migration) ficam com bookPageId = NULL — o renderer os
-- trata como "página solo". Postgres tolera múltiplos NULLs no unique, então
-- itens legados não colidem entre si.

-- CreateTable
CREATE TABLE "book_pages" (
    "id" TEXT NOT NULL,
    "bookId" TEXT NOT NULL,
    "storeId" TEXT NOT NULL,
    "order" INTEGER NOT NULL DEFAULT 0,
    "pageLayout" JSONB,
    "pageBackground" JSONB,
    "autoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "book_pages_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "book_pages_bookId_order_idx" ON "book_pages"("bookId", "order");

-- CreateIndex
CREATE INDEX "book_pages_storeId_idx" ON "book_pages"("storeId");

-- AddForeignKey
ALTER TABLE "book_pages"
ADD CONSTRAINT "book_pages_bookId_fkey"
FOREIGN KEY ("bookId") REFERENCES "books"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "book_pages"
ADD CONSTRAINT "book_pages_storeId_fkey"
FOREIGN KEY ("storeId") REFERENCES "stores"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AlterTable book_items: adiciona vínculo com BookPage + slotIndex
ALTER TABLE "book_items"
ADD COLUMN "bookPageId" TEXT,
ADD COLUMN "slotIndex"  INTEGER;

-- Remove o unique antigo (bookId, pdvPhotoId): a mesma foto pode entrar em
-- mais de uma página do mesmo book.
DROP INDEX IF EXISTS "book_items_bookId_pdvPhotoId_key";

-- Novo unique: slot único por página. Múltiplos NULLs em (bookPageId,
-- slotIndex) coexistem, preservando itens legados.
CREATE UNIQUE INDEX "book_items_bookPageId_slotIndex_key"
ON "book_items"("bookPageId", "slotIndex");

-- CreateIndex
CREATE INDEX "book_items_bookPageId_idx" ON "book_items"("bookPageId");

-- AddForeignKey
ALTER TABLE "book_items"
ADD CONSTRAINT "book_items_bookPageId_fkey"
FOREIGN KEY ("bookPageId") REFERENCES "book_pages"("id") ON DELETE CASCADE ON UPDATE CASCADE;
