import { Prisma } from "@/generated/prisma/client";
import prisma from "@/lib/db";
import { MAX_PER_PAGE, type PhotoOrientation } from "./distribute-photos";
import { ensurePhotoOrientations } from "./photo-aspects";

// Book "vivo": reconcilia as páginas de fotos AUTO de um book com as fotos
// APROVADAS do seu escopo (indústria + período), reusando a mesma distribuição
// do auto-generate. Adiciona aprovadas novas (inclusive de lojas novas), remove
// reprovadas/excluídas e reempacota as páginas. PRESERVA capa, página final,
// páginas extras (storeId null) e páginas editadas à mão (autoGenerated=false).
// O enquadramento (pan/zoom/fit) vive na própria PdvPhoto (photoAdjustments),
// então recriar os itens não perde ajuste. Só age em books ainda NÃO enviados
// (sentAt null) e fora de geração — depois de enviado, o book congela.

function monthRange(month: number, year: number) {
  return {
    from: new Date(Date.UTC(year, month - 1, 1)),
    to: new Date(Date.UTC(year, month, 1)),
  };
}

const photoTemplateKey = (o: PhotoOrientation, size: number) => `${o}-${size}`;

type DesiredPage = { orientation: PhotoOrientation; photoIds: string[] };

export async function resyncBook(
  bookId: string,
): Promise<{ added: number; removed: number; changed: boolean }> {
  const noop = { added: 0, removed: 0, changed: false };

  const book = await prisma.book.findUnique({
    where: { id: bookId },
    select: {
      id: true,
      organizationId: true,
      supplierId: true,
      periodMonth: true,
      periodYear: true,
      sentAt: true,
      status: true,
    },
  });
  if (!book || !book.supplierId || book.sentAt || book.status === "GENERATING") {
    return noop;
  }

  const { from, to } = monthRange(book.periodMonth, book.periodYear);
  const photos = await prisma.pdvPhoto.findMany({
    where: {
      organizationId: book.organizationId,
      supplierId: book.supplierId,
      approvalStatus: "APPROVED",
      promoterName: { not: null },
      capturedAt: { gte: from, lt: to },
    },
    orderBy: [{ storeId: "asc" }, { capturedAt: "asc" }],
    select: {
      id: true,
      storeId: true,
      photos: true,
      photoAspect: true,
      store: { select: { name: true } },
    },
  });

  const orientationByPhoto = await ensurePhotoOrientations(photos);

  // Agrupa por loja, separando por orientação (mesma regra do auto-generate).
  const groups = new Map<
    string,
    { storeName: string; landscape: string[]; portrait: string[] }
  >();
  for (const p of photos) {
    const g = groups.get(p.storeId) ?? {
      storeName: p.store.name,
      landscape: [],
      portrait: [],
    };
    if (orientationByPhoto.get(p.id) === "LANDSCAPE") g.landscape.push(p.id);
    else g.portrait.push(p.id);
    groups.set(p.storeId, g);
  }
  const orderedStores = Array.from(groups.entries()).sort(([, a], [, b]) =>
    a.storeName.localeCompare(b.storeName, "pt-BR"),
  );

  // Distribuição desejada por loja + sequência achatada (para detectar mudança).
  const desiredByStore = new Map<string, DesiredPage[]>();
  const desiredFlatByStore = new Map<string, string[]>();
  for (const [storeId, g] of orderedStores) {
    const pages: DesiredPage[] = [];
    const flat: string[] = [];
    for (const [ids, orientation] of [
      [g.landscape, "LANDSCAPE"] as const,
      [g.portrait, "PORTRAIT"] as const,
    ]) {
      const max = MAX_PER_PAGE[orientation];
      for (let i = 0; i < ids.length; i += max) {
        pages.push({ orientation, photoIds: ids.slice(i, i + max) });
      }
      flat.push(...ids);
    }
    if (pages.length > 0) {
      desiredByStore.set(storeId, pages);
      desiredFlatByStore.set(storeId, flat);
    }
  }

  // Páginas existentes (em ordem).
  const existingPages = await prisma.bookPage.findMany({
    where: { bookId },
    orderBy: { order: "asc" },
    select: {
      id: true,
      storeId: true,
      autoGenerated: true,
      items: { orderBy: { slotIndex: "asc" }, select: { pdvPhotoId: true } },
    },
  });

  // Sequência atual das páginas AUTO por loja.
  const existingFlatByStore = new Map<string, string[]>();
  for (const pg of existingPages) {
    if (!pg.autoGenerated || !pg.storeId) continue;
    const cur = existingFlatByStore.get(pg.storeId) ?? [];
    for (const it of pg.items) cur.push(it.pdvPhotoId);
    existingFlatByStore.set(pg.storeId, cur);
  }

  // Nada mudou (mesmas lojas e mesma sequência de fotos) ⇒ sai cedo.
  const sameStores =
    desiredFlatByStore.size === existingFlatByStore.size &&
    [...desiredFlatByStore.keys()].every((s) => existingFlatByStore.has(s));
  const sameSeq =
    sameStores &&
    [...desiredFlatByStore.entries()].every(([s, ids]) => {
      const cur = existingFlatByStore.get(s) ?? [];
      return cur.length === ids.length && cur.every((id, i) => id === ids[i]);
    });
  if (sameSeq) return noop;

  const desiredIds = new Set<string>([...desiredFlatByStore.values()].flat());
  const existingIds = new Set<string>([...existingFlatByStore.values()].flat());
  let added = 0;
  let removed = 0;
  for (const id of desiredIds) if (!existingIds.has(id)) added++;
  for (const id of existingIds) if (!desiredIds.has(id)) removed++;

  // Templates de foto da indústria (layout/fundo por orientação+tamanho).
  const templates = await prisma.bookPageTemplate.findMany({
    where: {
      organizationId: book.organizationId,
      supplierId: book.supplierId,
      kind: "PHOTO",
    },
    select: {
      photoOrientation: true,
      photoSize: true,
      layout: true,
      background: true,
    },
  });
  const photoTemplates = new Map<
    string,
    { layout: Prisma.JsonValue; background: Prisma.JsonValue | null }
  >();
  for (const t of templates) {
    if (t.photoOrientation && t.photoSize) {
      photoTemplates.set(photoTemplateKey(t.photoOrientation, t.photoSize), {
        layout: t.layout,
        background: t.background,
      });
    }
  }

  // Plano de ordem: percorre as páginas atuais; ao encontrar o 1º bloco AUTO de
  // uma loja, insere ali o bloco desejado dela; preserva extras/manuais na sua
  // posição. Lojas novas entram no fim.
  const emitted = new Set<string>();
  type Slot =
    | { kind: "preserve"; pageId: string }
    | { kind: "store"; storeId: string };
  const plan: Slot[] = [];
  for (const pg of existingPages) {
    if (!pg.autoGenerated || !pg.storeId) {
      plan.push({ kind: "preserve", pageId: pg.id });
      continue;
    }
    if (!emitted.has(pg.storeId)) {
      emitted.add(pg.storeId);
      if (desiredByStore.has(pg.storeId)) {
        plan.push({ kind: "store", storeId: pg.storeId });
      }
    }
  }
  for (const [storeId] of orderedStores) {
    if (!emitted.has(storeId) && desiredByStore.has(storeId)) {
      emitted.add(storeId);
      plan.push({ kind: "store", storeId });
    }
  }

  await prisma.$transaction(async (tx) => {
    // Remove as páginas AUTO de fotos (cascade nos itens). Extras/manuais ficam.
    await tx.bookPage.deleteMany({
      where: { bookId, autoGenerated: true, storeId: { not: null } },
    });

    let order = 0;
    let itemOrder = 0;
    for (const slot of plan) {
      if (slot.kind === "preserve") {
        await tx.bookPage.update({
          where: { id: slot.pageId },
          data: { order: order++ },
        });
        continue;
      }
      for (const page of desiredByStore.get(slot.storeId) ?? []) {
        const tmpl = photoTemplates.get(
          photoTemplateKey(page.orientation, page.photoIds.length),
        );
        const bookPage = await tx.bookPage.create({
          data: {
            bookId,
            storeId: slot.storeId,
            order: order++,
            autoGenerated: true,
            ...(tmpl
              ? {
                  pageLayout: tmpl.layout ?? Prisma.DbNull,
                  pageBackground: tmpl.background ?? Prisma.DbNull,
                }
              : {}),
          },
          select: { id: true },
        });
        await tx.bookItem.createMany({
          data: page.photoIds.map((pdvPhotoId, i) => ({
            bookId,
            bookPageId: bookPage.id,
            pdvPhotoId,
            slotIndex: i,
            order: itemOrder++,
          })),
        });
      }
    }

    // Conteúdo mudou ⇒ o PDF anterior fica desatualizado.
    await tx.book.update({
      where: { id: bookId },
      data: { generatedAt: null },
    });
  });

  return { added, removed, changed: true };
}

// Reconcilia todos os books NÃO enviados afetados por um conjunto de fotos
// (deduplicando por escopo indústria+período). Usado nos gatilhos de aprovação/
// reprovação/exclusão de fotos. Nunca lança — falha de resync não quebra a ação.
export async function resyncBooksForPhotos(
  organizationId: string,
  photos: { supplierId: string | null; capturedAt: Date }[],
): Promise<void> {
  const scopes = new Map<
    string,
    { supplierId: string; month: number; year: number }
  >();
  for (const p of photos) {
    if (!p.supplierId) continue;
    const month = p.capturedAt.getUTCMonth() + 1;
    const year = p.capturedAt.getUTCFullYear();
    scopes.set(`${p.supplierId}-${month}-${year}`, {
      supplierId: p.supplierId,
      month,
      year,
    });
  }
  if (scopes.size === 0) return;

  const books = await prisma.book.findMany({
    where: {
      organizationId,
      sentAt: null,
      status: { not: "GENERATING" },
      OR: [...scopes.values()].map((s) => ({
        supplierId: s.supplierId,
        periodMonth: s.month,
        periodYear: s.year,
      })),
    },
    select: { id: true },
  });

  for (const b of books) {
    try {
      await resyncBook(b.id);
    } catch (e) {
      console.error("[resyncBook] falhou para", b.id, e);
    }
  }
}

// Conveniência para os gatilhos de aprovação: recebe ids de fotos (que ainda
// existem no banco), resolve o escopo delas e reconcilia os books. Nunca lança.
export async function resyncBooksAfterPhotoChange(
  organizationId: string,
  photoIds: string[],
): Promise<void> {
  if (photoIds.length === 0) return;
  try {
    const photos = await prisma.pdvPhoto.findMany({
      where: { id: { in: photoIds }, organizationId },
      select: { supplierId: true, capturedAt: true },
    });
    await resyncBooksForPhotos(organizationId, photos);
  } catch (e) {
    console.error("[resyncBooksAfterPhotoChange]", e);
  }
}
