import {
  Apple,
  Baby,
  Banana,
  Bath,
  Beef,
  Beer,
  BookOpen,
  Bone,
  Cake,
  Candy,
  Car,
  Carrot,
  Cherry,
  Citrus,
  Coffee,
  Cookie,
  Croissant,
  CupSoda,
  Drumstick,
  Dumbbell,
  Egg,
  Fish,
  Flower2,
  Gamepad2,
  Gift,
  Grape,
  Ham,
  Hammer,
  Headphones,
  HeartPulse,
  House,
  IceCreamCone,
  Lamp,
  Laptop,
  Leaf,
  type LucideIcon,
  Milk,
  Package,
  PawPrint,
  Pencil,
  Pill,
  Pizza,
  Popcorn,
  Salad,
  Sandwich,
  Scissors,
  Shirt,
  ShoppingBasket,
  Shrimp,
  Smartphone,
  Snowflake,
  Sofa,
  Soup,
  Sparkles,
  SprayCan,
  Sprout,
  Tag,
  Tv,
  Utensils,
  Wheat,
  Wine,
  Wrench,
} from "lucide-react";

/**
 * A galeria de ícones das categorias da vitrine.
 *
 * O banco guarda só a CHAVE (`Category.icon`), nunca o componente: trocar o
 * desenho de um ícone aqui atualiza todas as lojas que o escolheram, e uma
 * chave que deixar de existir cai no ícone neutro em vez de quebrar a página.
 */
export const ICONES_DE_CATEGORIA: Record<
  string,
  { rotulo: string; Icone: LucideIcon }
> = {
  frutas: { rotulo: "Frutas", Icone: Apple },
  banana: { rotulo: "Banana", Icone: Banana },
  citricos: { rotulo: "Cítricos", Icone: Citrus },
  uva: { rotulo: "Uva", Icone: Grape },
  cereja: { rotulo: "Cereja", Icone: Cherry },
  legumes: { rotulo: "Legumes", Icone: Carrot },
  verduras: { rotulo: "Verduras", Icone: Salad },
  hortifruti: { rotulo: "Hortifruti", Icone: Sprout },
  carnes: { rotulo: "Carnes", Icone: Beef },
  frango: { rotulo: "Frango", Icone: Drumstick },
  frios: { rotulo: "Frios", Icone: Ham },
  peixes: { rotulo: "Peixes", Icone: Fish },
  frutosDoMar: { rotulo: "Frutos do mar", Icone: Shrimp },
  ovos: { rotulo: "Ovos", Icone: Egg },
  laticinios: { rotulo: "Laticínios", Icone: Milk },
  congelados: { rotulo: "Congelados", Icone: Snowflake },
  padaria: { rotulo: "Padaria", Icone: Croissant },
  graos: { rotulo: "Grãos", Icone: Wheat },
  mercearia: { rotulo: "Mercearia", Icone: ShoppingBasket },
  sopas: { rotulo: "Enlatados e sopas", Icone: Soup },
  lanches: { rotulo: "Lanches", Icone: Sandwich },
  pizza: { rotulo: "Pizza", Icone: Pizza },
  petiscos: { rotulo: "Petiscos", Icone: Popcorn },
  doces: { rotulo: "Doces", Icone: Candy },
  biscoitos: { rotulo: "Biscoitos", Icone: Cookie },
  bolos: { rotulo: "Bolos", Icone: Cake },
  sorvetes: { rotulo: "Sorvetes", Icone: IceCreamCone },
  cafe: { rotulo: "Café e chás", Icone: Coffee },
  bebidas: { rotulo: "Bebidas", Icone: CupSoda },
  cervejas: { rotulo: "Cervejas", Icone: Beer },
  vinhos: { rotulo: "Vinhos e destilados", Icone: Wine },
  bebe: { rotulo: "Bebê", Icone: Baby },
  pet: { rotulo: "Pet", Icone: PawPrint },
  petOsso: { rotulo: "Petiscos pet", Icone: Bone },
  limpeza: { rotulo: "Limpeza", Icone: SprayCan },
  higiene: { rotulo: "Higiene", Icone: Bath },
  beleza: { rotulo: "Beleza", Icone: Sparkles },
  saude: { rotulo: "Saúde", Icone: HeartPulse },
  farmacia: { rotulo: "Farmácia", Icone: Pill },
  natural: { rotulo: "Natural", Icone: Leaf },
  flores: { rotulo: "Flores e jardim", Icone: Flower2 },
  casa: { rotulo: "Casa", Icone: House },
  moveis: { rotulo: "Móveis", Icone: Sofa },
  iluminacao: { rotulo: "Iluminação", Icone: Lamp },
  utilidades: { rotulo: "Utilidades", Icone: Utensils },
  ferramentas: { rotulo: "Ferramentas", Icone: Wrench },
  construcao: { rotulo: "Construção", Icone: Hammer },
  automotivo: { rotulo: "Automotivo", Icone: Car },
  moda: { rotulo: "Moda", Icone: Shirt },
  armarinho: { rotulo: "Armarinho", Icone: Scissors },
  celulares: { rotulo: "Celulares", Icone: Smartphone },
  informatica: { rotulo: "Informática", Icone: Laptop },
  eletronicos: { rotulo: "Eletrônicos", Icone: Tv },
  audio: { rotulo: "Áudio", Icone: Headphones },
  games: { rotulo: "Games", Icone: Gamepad2 },
  papelaria: { rotulo: "Papelaria", Icone: Pencil },
  livros: { rotulo: "Livros", Icone: BookOpen },
  esportes: { rotulo: "Esportes", Icone: Dumbbell },
  presentes: { rotulo: "Presentes", Icone: Gift },
  embalagens: { rotulo: "Embalagens", Icone: Package },
  outros: { rotulo: "Outros", Icone: Tag },
};

/** O ícone da categoria, ou o neutro quando não há escolha (ou ela sumiu). */
export function iconeDaCategoria(chave: string | null | undefined): LucideIcon {
  return (chave && ICONES_DE_CATEGORIA[chave]?.Icone) || Tag;
}
